# Generated by Django 5.0.6 on 2024-06-13 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del grupo')),
                ('descripcion', models.TextField(max_length=100, verbose_name='Descripcion')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255, unique=True)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(null=True)),
                ('imagen_perfil', models.ImageField(null=True, upload_to='perfiles')),
                ('rol', models.CharField(choices=[('lector', 'Lector'), ('colaborador', 'Colaborador')], default='lector', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(max_length=50, verbose_name='Contenido')),
                ('video', models.FileField(blank=True, upload_to='', verbose_name='video')),
                ('imagen', models.ImageField(blank=True, upload_to='', verbose_name='Foto')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicacion')),
                ('grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
